In [110]:
# 국어점수입력함수

# def inputnum():
#   import numpy as np
#   import random

#   d = []
#   total_d = []
#   for k in range(6):
#     for i in range(5):
#       raw_data = input("{}학년 {} 반의 점수를 입력해 주세요 : ".format(k+1, i+1)).split();
#       # raw_data = np.random.randint(0, 100, size = 5)
#       int_raw_data = [int(x) for x in raw_data]
#       d.append(int_raw_data)
#   total_d.append(d)
    
#   return total_d

# 아래는 랜덤 생성
def inputnum():
  import numpy as np
  import random

  d = []
  total_d = []
  for k in range(6):
    for i in range(5):
      # raw_data = input("{}학년 {} 반의 점수를 입력해 주세요 : ".format(k+1, i+1)).split();
      raw_data = np.random.randint(0, 100, size = 5)
      int_raw_data = [int(x) for x in raw_data]
      d.append(int_raw_data)
  total_d.append(d)
    
  return total_d

In [28]:
# 점수검증함수

def correct(inputnum):
  A = inputnum()
  error = []
  for i in range(6):
   for j in range(5):
     for k in range(5):
       if  A[i][j][k]< 0 or A[i][j][k] > 100:
         print(i,j,k,A[i][j][k], "은 잘못된 값")
         error.append([i,j,k])
     
  return error

In [31]:
# 점수수정함수

def edit(inputnum):
  A = inputnum()  
  i = input("고칠 곳의 인덱스를 입력하세요").split();
  i0 = (int(i[0]))
  i1 = (int(i[1]))
  i2 = (int(i[2]))
  
  j = input("인덱스의 값을 어떻게 바꿀까요?").split();
  j0 = int(j[0])

  A[i0][i1][i2] = j0
  
  return A

In [117]:
# 반 별 평균 리스트
def average(inputnum):
  A = inputnum()
  average = []
  count = 0
  sum = 0

  for i in range(len(A)):     
    for j in range(len(A[i])):     
      for k in range(len(A[i][j])): 
        sum += A[i][j][k]
      average.append(sum/5)
      sum = 0
  return average # 반 별 평균 리스트

In [310]:
# 평균점수가 가장 높은 반과 낮은 반
def big_small(inputnum, average):
  A=inputnum()
  AV = average(inputnum)
  big = AV[0]
  small = AV[0]

  for score in AV:
    if big < score:
      big = score
  biggest = AV.index(big) 

  if biggest < 5: # 0 1 2 3 4
    print("평균 점수가 가장 높은 반은 1학년", biggest+1,'반')
  elif 4 < biggest < 10: # 5 6 7 8 9
    print("평균 점수가 가장 높은 반은 2학년", biggest-4,'반')
  elif 9 < biggest < 14: # 9 10 11 12 13
    print("평균 점수가 가장 높은 반은 3학년", biggest-8,'반')
  elif 13 < biggest < 19: # 14 15 16 17 18
    print("평균 점수가 가장 높은 반은 4학년", biggest-13,'반')
  elif 18 < biggest < 24: # 19 20 21 22 23
    print("평균 점수가 가장 높은 반은 5학년", biggest-18,'반')
  elif 9 < biggest < 14: # 24 25 26 27 28
    print("평균 점수가 가장 높은 반은 6학년", biggest-23,'반')
    

  for score in AV:
    if small > score:
      small = score
  smallest = AV.index(small)
  
  if smallest < 5: # 0 1 2 3 4
    print("평균 점수가 가장 낮은 반은 1학년", smallest+1,'반')
  elif 4 < smallest < 10: # 5 6 7 8 9
    print("평균 점수가 가장 낮은 반은 2학년", smallest-4,'반')
  elif 9 < smallest < 14: # 9 10 11 12 13
    print("평균 점수가 가장 낮은 반은 3학년", smallest-8,'반')
  elif 13 < smallest < 19: # 14 15 16 17 18
    print("평균 점수가 가장 낮은 반은 4학년", smallest-13,'반')
  elif 18 < smallest < 24: # 19 20 21 22 23
    print("평균 점수가 가장 낮은 반은 5학년", smallest-18,'반')
  elif 9 < smallest < 14: # 24 25 26 27 28
    print("평균 점수가 가장 낮은 반은 6학년", smallest-23,'반')

In [309]:
# 보충수업학생명단
def practice(inputnum, average):
  A=inputnum()
  AV = average(inputnum)
  sum1 = 0
  sum2=0
  sum3 = 0
  sum4=0
  sum5=0
  sum6=0
  ave1 =0
  ave2=0
  ave3=0
  ave4=0
  ave5=0
  ave6=0
  ave = []

  # 학년 별 평균

  sum1 += AV[0] + AV[1] + AV[2] + AV[3] + AV[4]
  sum2 += AV[5] + AV[6] + AV[7] + AV[8] + AV[9]
  sum3 += AV[10] + AV[11] + AV[12] + AV[13] + AV[14]
  sum4 += AV[15] + AV[16] + AV[17] + AV[18] + AV[19]
  sum5 += AV[20] + AV[21] + AV[22] + AV[23] + AV[24]
  sum6 += AV[25] + AV[26] + AV[27] + AV[28] + AV[29]

  ave1 = sum1/5 
  ave2 = sum2/5
  ave3 = sum3/5
  ave4 = sum4/5
  ave5 = sum5/5
  ave6 = sum6/5

  ave.append(ave1)
  ave.append(ave2)
  ave.append(ave3)
  ave.append(ave4)
  ave.append(ave5)
  ave.append(ave6)

  # 학년의 평균 점수보다 낮은 점수를 가진 학생은?

# 1학년
  for i in range(0,5):
    A1 = A[0][i]
    for val in A1:
     if val < ave[0]:
       print("1학년",i+1,"반",A1.index(val)+1,'번')
# 2학년
  for i in range(5,10):
    A1 = A[0][i]
    for val in A1:
     if val < ave[0]:
       print("2학년",i-4,"반",A1.index(val)+1,'번')
# 3학년
  for i in range(10,15):
    A1 = A[0][i]
    for val in A1:
     if val < ave[0]:
       print("3학년",i-9,"반",A1.index(val)+1,'번')
# 4학년
  for i in range(15,20):
    A1 = A[0][i]
    for val in A1:
     if val < ave[0]:
       print("4학년",i-14,"반",A1.index(val)+1,'번')
# 5학년
  for i in range(20,25):
    A1 = A[0][i]
    for val in A1:
     if val < ave[0]:
       print("5학년",i-19,"반",A1.index(val)+1,'번')
# 6학년
  for i in range(25,30):
    A1 = A[0][i]
    for val in A1:
     if val < ave[0]:
       print("6학년",i-24,"반",A1.index(val)+1,'번')